### ISSUE TITLE
blocking problem in NodeBB 1.18.X

### ISSUE THREAD

**Issue by AliCihan** [oplik0/nodebb-plugin-two-way-block#58]
Hi @oplik0 , how are you? Thanks again for the plugin.

We are using NodeBB 1.18.6 with Persona 11.2.21 and two-way block plugin 1.3.1

 In case it is easy to fix, here are some problems with the plugin...

Let's say User A blocked User B, 

User A does not see any posts of User B, or any topics started by User B; which is how it should work; however "in recent cards" (we use 2.0.19) User A can see the topic User B started and what he/she wrote. 

Additionally, User B, unfortunately, can see what User A wrote if that is the last post (on the /recent page) of the topic, however, it works OK when User B clicks the topic title, User B cannot see the post of User A on the topic. Additionally, like the problem above User B can see the topic User A started and what he/she wrote. 

So, if it is possible; 

* Can those topics on recent cards be blocked? 
* And, can you prevent User B see the last post of the topic on /recent page if that post belongs to someone blocked User B.

Thanks a lot.

**Comment by oplik0** [comment]
I'll look into this after Christmas, hopefully I will find time to do this before end of the year :)

**Comment by AliCihan** [comment]
Thanks a lot @oplik0 , you are the best. 

I have one more question (more like a feature request if you see this as a good addition to the plugin). We use the "browsing users" plugin, so avatars of the users browsing the same topic can be seen.  Do you think it is easy to block the appearance of the avatar of the blocked person on these pages?

So, in the end, this plugin will be more like the "blocking" function of the many social media sites. You do not see the blocked person and also his/her posts; and vice versa...

**Comment by oplik0** [comment]
I'll have to look into how the browsing-users plugin works again, but IIRC it didn't work on per-user basis. I'll see what I can do though.

**Comment by oplik0** [comment]
So, turns out it broke with NodeBB updates. I remembered that I worked on getting teasers to work!

I'll work on the browsing-users now, but I'll make a separate issue for that in case I'm not able to finish it today.

**Comment by AliCihan** [comment]
@oplik0 thanks a lot.

**Comment by oplik0** [comment]
Should be fixed in v1.4.0: 
* GitHub release: https://github.com/oplik0/nodebb-plugin-two-way-block/releases/tag/v1.4.0 
* NPM: https://www.npmjs.com/package/nodebb-plugin-two-way-block/v/1.4.0

**Comment by AliCihan** [comment]
Hi @oplik0 , thanks a lot. 

It looks like it is working well on /recent page. However last topics on /categories can be seen, and we are having errors on the log (which might be related). 


```
[nodebb-plugin-two-way-block] encountered an error while processing teasers: TypeError: Cannot read properties of undefined (reading 'uid')
    at /home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:58:67
    at Array.map (<anonymous>)
    at Object.twoWayBlock.filterTeasers [as method] (/home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:58:17)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at fireMethod (/home/fsuzer/nodebb/src/plugins/hooks.js:137:11)
    at Object.fireFilterHook [as filter] (/home/fsuzer/nodebb/src/plugins/hooks.js:168:12)
    at Hooks.fire (/home/fsuzer/nodebb/src/plugins/hooks.js:105:17)
    at Topics.getTeasers (/home/fsuzer/nodebb/src/topics/teaser.js:89:18)
    at async Promise.all (index 0)
```

**Comment by oplik0** [comment]
I wasn't actually able to replicate that issue, but tried to fix it based on the error log. If it still persists in 1.4.1 I'll try harder to find what might be going on :) Also [nodebb-plugin-browsing-users@2.0.1](https://github.com/barisusakli/nodebb-plugin-browsing-users) now doesn't show blocked people (and with this plugin also doesn't show people who blocked you)

**Comment by AliCihan** [comment]
Hi @oplik0 , with 1.4.1 we do not get that error in the logs anymore. Thanks again 🙏

**Comment by AliCihan** [comment]
Hi @oplik0 , sorry for bothering you again. It works perfectly with the "browsing users" plugin. Thanks a lot for the integration. 

And additionally, the plugin works perfectly on the threads, as well as on the /recent page... 

However, we have problems in two places... the person who blocked you can be seen in the "recent cards" and also in the "most recent post" of the categories page(in teasers)... 

When I refresh those pages when the blocking person is the last post owner, I keep getting these errors: 

```
2022-01-15T03:16:36.077Z [4567/9407] - [31merror[39m: [nodebb-plugin-two-way-block] encountered an error while processing teasers: TypeError: Cannot read properties of undefined (reading 'uid')
    at /home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:60:68
    at Array.map (<anonymous>)
    at Object.twoWayBlock.filterTeasers [as method] (/home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:60:18)
    at fireMethod (/home/fsuzer/nodebb/src/plugins/hooks.js:137:11)
    at Object.fireFilterHook [as filter] (/home/fsuzer/nodebb/src/plugins/hooks.js:168:12)
    at Hooks.fire (/home/fsuzer/nodebb/src/plugins/hooks.js:105:17)
    at Topics.getTeasers (/home/fsuzer/nodebb/src/topics/teaser.js:88:18)
    at async Promise.all (index 0)
    at loadTopics (/home/fsuzer/nodebb/src/topics/index.js:93:80)
    at async Promise.all (index 0)
2022-01-15T03:21:47.396Z [4567/9407] - [31merror[39m: [nodebb-plugin-two-way-block] encountered an error while processing teasers: TypeError: Cannot read properties of undefined (reading 'uid')
    at /home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:60:68
    at Array.map (<anonymous>)
    at Object.twoWayBlock.filterTeasers [as method] (/home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:60:18)
    at fireMethod (/home/fsuzer/nodebb/src/plugins/hooks.js:137:11)
    at Object.fireFilterHook [as filter] (/home/fsuzer/nodebb/src/plugins/hooks.js:168:12)
    at Hooks.fire (/home/fsuzer/nodebb/src/plugins/hooks.js:105:17)
    at Topics.getTeasers (/home/fsuzer/nodebb/src/topics/teaser.js:88:18)
    at async Promise.all (index 0)
    at loadTopics (/home/fsuzer/nodebb/src/topics/index.js:93:80)
    at async Promise.all (index 0)
2022-01-15T03:23:06.008Z [4567/9407] - [31merror[39m: [nodebb-plugin-two-way-block] encountered an error while processing teasers: TypeError: Cannot read properties of undefined (reading 'uid')
    at /home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:60:68
    at Array.map (<anonymous>)
    at Object.twoWayBlock.filterTeasers [as method] (/home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:60:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at fireMethod (/home/fsuzer/nodebb/src/plugins/hooks.js:137:11)
    at Object.fireFilterHook [as filter] (/home/fsuzer/nodebb/src/plugins/hooks.js:168:12)
    at Hooks.fire (/home/fsuzer/nodebb/src/plugins/hooks.js:105:17)
    at Topics.getTeasers (/home/fsuzer/nodebb/src/topics/teaser.js:88:18)
    at async Promise.all (index 0)
2022-01-15T03:23:36.725Z [4567/9407] - [31merror[39m: [nodebb-plugin-two-way-block] encountered an error while processing teasers: TypeError: Cannot read properties of undefined (reading 'uid')
    at /home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:60:68
    at Array.map (<anonymous>)
    at Object.twoWayBlock.filterTeasers [as method] (/home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:60:18)
    at fireMethod (/home/fsuzer/nodebb/src/plugins/hooks.js:137:11)
    at Object.fireFilterHook [as filter] (/home/fsuzer/nodebb/src/plugins/hooks.js:168:12)
    at Hooks.fire (/home/fsuzer/nodebb/src/plugins/hooks.js:105:17)
    at Topics.getTeasers (/home/fsuzer/nodebb/src/topics/teaser.js:88:18)
    at async Promise.all (index 0)
    at loadTopics (/home/fsuzer/nodebb/src/topics/index.js:93:80)
    at async Promise.all (index 0)

```

I appreciate your help.

**Comment by oplik0** [comment]
@AliCihan fixed it in 1.4.2. I missed one place where I also referenced uid in the way it was included previously in teaser data (now it's under `teaser.user.uid` instead of just `teaser.uid`)

**Comment by AliCihan** [comment]
thanks @oplik0 , I have upgraded and restarted, this time instead of "(reading 'uid')" error, we get "(reading 'user')" error... 

```
2022-01-16T18:26:05.850Z [4567/24177] - [31merror[39m: [nodebb-plugin-two-way-block] encountered an error while processing teasers: TypeError: Cannot read properties of undefined **(reading 'user')**
    at /home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:60:68
    at Array.map (<anonymous>)
    at Object.twoWayBlock.filterTeasers [as method] (/home/fsuzer/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:60:18)
    at fireMethod (/home/fsuzer/nodebb/src/plugins/hooks.js:137:11)
    at Object.fireFilterHook [as filter] (/home/fsuzer/nodebb/src/plugins/hooks.js:168:12)
    at Hooks.fire (/home/fsuzer/nodebb/src/plugins/hooks.js:105:17)
    at Topics.getTeasers (/home/fsuzer/nodebb/src/topics/teaser.js:88:18)
    at async Promise.all (index 0)
    at loadTopics (/home/fsuzer/nodebb/src/topics/index.js:93:80)
    at async Promise.all (index 0)
```

**Comment by oplik0** [comment]
Alright, should be fixed correctly now :)
However, it still won't *entirely* work with recent cards after all. If a topic was created by and contains only replies from blocked users/users who blocked you it will show the original post.
This is an issue with the recent cards plugin and explicitly removing that initial post causes even worse issues (it shows a post from a different topic under the one that should be blocked for some reason)

**Comment by AliCihan** [comment]
@oplik0 thanks a lot. I believe the recent cards part is ok.
 
Thanks to you, we have eliminated many possible interactions between two users. Especially on regular topics, browsing user lists, and on the most recent reply part. That is good enough :) Many thanks 🙏 

I have a quick question related to what you wrote just above, when there is a newly created topic by a user that blocked you, in the previous versions of the plugin we were not seeing the teasers on /categories page, instead it was showing the topic that comes one before... But these new versions, if that is the only post on the newly created topic, it shows the person and his/her post even in the teaser. Do you think it is tricky to reverse this to the old version? If it is tricky or breaks some other things, it is ok though.

**Comment by oplik0** [comment]
I'll have to check again how it's handled, but I'm fairly sure it was a change in NodeBB. Since all I'm doing is passing an empty teaser array if whole topic should be blocked, and that behavior hasn't changed.
I'll look into it later, but not today unfortunately.

**Comment by oplik0** [comment]
Yeah, the issue is that if I try to add teasers from different topics to the mix things start mixing and you start seeing topics with teasers from different ones.
In the end the most reasonable behavior I was able to get here happens when, if all teasers are blocked, I return `undefined`, as then recent cards don't break as badly (they show an empty teaser instead of shifting all further teasers a card left), and stock NodeBB teaser spots show `no new posts` instead of the blocked teaser.

It's not perfect, but NodeBB and recent cards would need to be modified for this to work properly, and I don't really want to undertake that effort myself.

**Comment by AliCihan** [comment]
dear @oplik0 , thank you very much. 🙏 
this 1.4.4 version works perfectly; teasers are fixed and empty card in recent cards is no problem at all... Additionally, our log is clear, there is no more error coming from the two-way-block plugin. Thank again, you are the best 👍
